version: "3.9"

services:
  worker:
    build: worker
    networks:
      - back-tier
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOSTNAME=db
      - REDIS_HOSTNAME=redis
    restart: always
  poll:
    build: poll
    networks:
      - poll-tier
    ports:
      - "5000:80"
    environment:
      - FLASK_APP=app.py
    restart: always
  result:
    build: result
    networks:
      - result-tier
    ports:
      - "5001:80"
    environment:
      - PORT_RESULT=80
      - DB_HOSTNAME_RESULT=db
    restart: always
  redis:
    networks:
      - poll-tier
      - back-tier
    image: redis:latest
    ports:
      - "6379:6379"
    restart: on-failure
  db:
    image: postgres:13.0
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgreql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - result-tier
      - back-tier
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
